### ISSUE TITLE
Iteration

### ISSUE THREAD

**Issue by JericoFX** [Annalouu/an-engineswap#6]
Hi Ann, i dont know if is intended but in this line https://github.com/Annalouu/an-engineswap/blob/main/client/cl_main.lua#L69 you run a loop and inside the loop is the call of the playerData, is that for a reason?, because each iteration you call the QBCore object.

**Comment by Annalouu** [comment]
It was from the very first version of the script and it stayed there since it worked and didnt cause any issues, if it aint broke dont fix it xD
