### ISSUE TITLE
Engine Sound Not Saving

### ISSUE THREAD

**Issue by ahmoge** [Annalouu/an-engineswap#9]
Hello. i just downloaded script and after buying the engine sound it changed, but after i stored it on the [garage](https://github.com/JonasDev17/qb-garages) and getting it back the car from the garage the engine sound disappears. i have checked the database and it is there on the plate.
![image](https://github.com/Annalouu/an-engineswap/assets/121356172/fa4bd458-0725-4d84-9f1b-a276dd39f7a5)

**Comment by Annalouu** [comment]
For some reason people can't seem to be able to use it with that garage while i myself use it and it works great

**Comment by ahmoge** [comment]
i am one of them :(. i dont want to go back to original qb-garages,

**Comment by ahmoge** [comment]
Hello mam Annalouu. I think i found the cause of the engine sound not applying after i stored / pulled out the car from garage. when i set the "Config.SpawnVehiclesServerside = false " it will use the changed engine sound, but if i set it to "true" it wont apply the sound.

**Comment by Annalouu** [comment]
Thats your garages issue, not my script. cuz vehicles needs to be handled client wise to be able to change the sound
